// import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/navbar'

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faThumbsUp } from '@fortawesome/free-solid-svg-icons'
import { faLinkedin } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'





export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <script src="https://kit.fontawesome.com/135bdf8c55.js" crossOrigin="anonymous"></script>
      <body>
        <Navbar />  {/* <-- Your glassy responsive navbar */}
        {children}
      </body>
      <section id="about" className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-flow-col grid-rows-2 gap-4">
          <div className="col-span-2 ">
            <h1 className="text-5xl text-[--color-text]">Muhammad Guarddin</h1>

            <a className='a_icon'><FontAwesomeIcon  icon={faThumbsUp} className="fa-icon fa-icon--sm" /></a>
            <a className='a_icon'><FontAwesomeIcon icon={faLinkedin} className="fa-icon fa-icon--sm" /></a>
            <a className='a_icon'><FontAwesomeIcon icon={faInstagram} className="fa-icon fa-icon--sm" /></a>

            <p className="w-full py-8 text-[--color-text] text-wrap text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
          </div>
          <div className="col-span-1 row-span-2 ...">
            <p className="w-full text-[--color-text] text-wrap text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
          
          </div>
          <div className="row-span-3">
            <img className="h-100 w-90 object-cover mask-r-from-30% rounded-lg" src="/img/wow.jpg" alt="Sunset in the mountains"></img>
          </div>
        </div>

        <h1 className="text-3xl font-bold mb-4">Hi! I'm Muhammad Guarddin</h1>
       
        <p className="text-[--color-text]">
          This is your content area. Scroll to see the sticky, glassy navbar stay put.
        </p>
      </section>
    </html>
  )
}
