// import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/navbar'

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faThumbsUp } from '@fortawesome/free-solid-svg-icons'
import { faLinkedin } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'





export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <script src="https://kit.fontawesome.com/135bdf8c55.js" crossOrigin="anonymous"></script>
      <body>
        <Navbar />  {/* <-- Your glassy responsive navbar */}
        {children}
      </body>
      <section id="about" className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold mb-4">Hi! I'm Muhammad Guarddin</h1>
       <FontAwesomeIcon icon={faThumbsUp} />
       <FontAwesomeIcon icon={faLinkedin} />
       <FontAwesomeIcon icon={faInstagram} />

        <p className="text-[--color-text]">
          This is your content area. Scroll to see the sticky, glassy navbar stay put.
        </p>
      </section>
    </html>
  )
}
